language: node_js
sudo: true
dist: trusty
node_js:
  - 10
  - 12
install:
  - npm i
  - npm i -g codecov
script:
  - npm test
notifications:
  email:
    on_failure: change
after_success:
  - codecov
